In [380]:
import pandas as pd
import numpy as np

In [381]:
text_df = pd.read_csv(r'D:\DA_data\Data_analytics\power Bi project\Upi Transaction\Cleaning_prectice\Data\Raw\text_data_2.csv')

In [382]:
text_df.head(10)

,id,full_name,email,phone_number,gender,country,city,address,job_title,department,company_name,product_category,feedback_text,status,notes
0,122,"Brown, Priya",NaN,7857907785,F,usa,London,539 park street.,HR Executive,ENGINEERING,StartUp Hub,clothing,NaN,pending,NaN
1,110,"Walker, Emma",walker..emma@gmail,(081) 369-1543,NaN,IN,New York,NaN,Product Manager,Finance,Bright Future LLC,sports and fitness,Not satisfied &amp; want refund,Active,none
2,128,JAMES SHARMA,NaN,(397) 035-7086,F,india,bangalore,"329 MG Road, Suite 12",data analyst,Sales,Bright Future LLC,CLOTHING,great service will buy again,inactive,Pending review
3,133,"Nair, Sneha",nair..sneha@gmail,7507137449,male,US,bangalore,787 Park Street,PRODUCT MANAGER,engineering,bright future llc,Home & Kitchen,"Great service, will buy again!!!",inactive,NaN
4,69,"Brown, Divya",NaN,(857) 893-3331,NaN,U.K.,NYC,NaN,Data Analyst,marketing,Tech Solutions Inc.,NaN,Not satisfied &amp; want refund,active,NaN
5,130,Priya Smith,priya.smithATgmail,NaN,F,australia,Delhi,NaN,SR SOFTWARE ENGINEER,engineering,TECH SOLUTIONS INC,ELECTRONICS,NaN,pending,pending review
6,98,sophia.reddy,sophia.reddy@gmail,NaN,NaN,NaN,New Delhi,NaN,Sales Executive,HR,StartUp Hub,Sports & Fitness,NaN,Inactive,FOLLOW UP REQUIRED
7,70,Noah Gupta,noah..gupta612@yahoo.com,548.901.0397,Female,UK,london,NaN,Data Analyst,Sales,Tech Solutions Inc.,books,"Product was okay, delivery was late.",ACTIVE,Pending review
8,22,"Meera, Gupta",meera..guptaATgmailDOTcom,(187) 463-3191,NaN,UK,NYC,NaN,hr executive,marketing,global traders pvt ltd,NaN,Not satisfied and want a refund,Active,FOLLOW UP REQUIRED
9,71,Aarav Verma,NaN,771.961.1459,NaN,IN,NaN,460 Park Street,hr executive,marketing,startup hub,clothing,GREAT SERVICE!!! WILL BUY AGAIN,Active,-

In [383]:
text_df .tail(7)

,id,full_name,email,phone_number,gender,country,city,address,job_title,department,company_name,product_category,feedback_text,status,notes
139,74,Noah-Singh,noah-singh@outlook.com,NaN,FEMALE,NaN,Bangalore,NaN,Data Analyst,NaN,Acme and Co,Home & Kitchen,product was okay...delivery was LATE,A,NaN
140,52,Sophia Patel.,sophia.patelATyahooDOTcom,6160534468,M,CANADA,New Delhi,NaN,software engineer,Finance,bright future llc,books,excellent quality highly recommend,ACTIVE,NaN
141,127,"Aarav, Patel",NaN,6672176728,NaN,usa,Delhi,697 park street.,HR Executive,finance,NaN,beauty,great service will buy again,active,NaN
142,99,vikram.walker,NaN,01862297631,Male,Canada,toronto,918 park street.,PRODUCT MANAGER,Marketing,Tech Solutions Inc,Books,"Excellent quality, highly recommend!",active,FOLLOW UP REQUIRED
143,17,"Wilson, Olivia",invalid.email,4335326502,male,UK,london,NaN,NaN,sales,bright future llc,clothing,NaN,Inactive,Follow up next week
144,75,arjun.iyer,arjun.iyer@gmail.com,(620) 420-7858,FEMALE,India,NaN,"294 MG Road,",marketing specialist,Marketing,Acme and Co,Home&Kitchen,GREAT SERVICE!!! WILL BUY AGAIN,ACTIVE,VIP customer
145,83,"Clark, Karan",invalid.email,06052358574,MALE,U.K.,mumbai,"791 MG Road, Apt 4B",hr executive,product,StartUp Hub,electronics,excellent quality highly recommend,INACTIVE,NaN

In [384]:
text_df['id'].unique()
text_df.sort_values(by = 'id', ascending=True, inplace=True)
text_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 146 entries, 97 to 65
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                146 non-null    int64
 1   full_name         146 non-null    object
 2   email             102 non-null    object
 3   phone_number      113 non-null    object
 4   gender            111 non-null    object
 5   country           134 non-null    object
 6   city              137 non-null    object
 7   address           66 non-null     object
 8   job_title         137 non-null    object
 9   department        134 non-null    object
 10  company_name      135 non-null    object
 11  product_category  138 non-null    object
 12  feedback_text     123 non-null    object
 13  status            137 non-null    object
 14  notes             109 non-null    object
dtypes: int64(1), object(14)
memory usage: 18.2+ KB

In [385]:

def fix_name_order(name):
    if ',' in str(name):
        last, first = [p.strip() for p in name.split(',', 1)]
        return f"{first} {last}"
    return name

text_df['full_name'] = text_df['full_name'].astype(str).apply(fix_name_order)

In [386]:
# Cleaning and Fix full_name 
text_df['full_name'] = text_df['full_name'].str.strip().str.replace(r'[,.-]',' ', regex=True).str.replace(r'\s+', ' ', regex=True)
text_df['full_name']= text_df['full_name'].str.title()
text_df['full_name'].unique()

array(['John Singh', 'Divya Verma', 'Divya Gupta', 'Rohan Verma',
       'Sophia Chopra', 'Liam Brown', 'Johnson Isabella', 'Rohan Chopra',
       'Emma Johnson', 'Anjali Reddy', 'John Chopra', 'William Clark',
       'Karan Anderson', 'John Taylor', 'Olivia Chopra', 'Priya Clark',
       'Olivia Wilson', 'James Verma', 'Emma Patel', 'Meera Verma',
       'Gupta Meera', 'Ava Anderson', 'Priya Malhotra', 'Meera Malhotra',
       'John Iyer ', 'Vikram Verma', 'Divya Chopra', 'John Nair',
       'Ava Nair ', 'Karan Brown', 'Sneha Malhotra', 'Aarav Wilson',
       'Meera Taylor', 'Liam Gupta ', 'Nair Isabella', 'Clark Noah',
       'William Gupta', 'William Iyer ', 'Gupta John', 'Emma Malhotra',
       'Hall Emma', 'Priya Wilson', 'Arjun Iyer', 'Anjali Johnson',
       'Karan Malhotra ', 'Rohan Walker', 'Sophia Patel ', 'Sophia Smith',
       'Sneha Reddy', 'Aarav Iyer', 'John Sharma', 'William Patel ',
       'Karan Wilson', 'Isabella Gupta ', 'Anjali Hall',
       'Isabella Sharma', 'Smith Emma', 'Meera Singh', 'Anjali Verma',
       'Vikram Wilson', 'Wilson Sophia', 'Noah Chopra ', 'Divya Brown',
       'Noah Gupta', 'Aarav Verma', 'Priya Lewis', 'Aarav Anderson',
       'Noah Singh', 'Anjali Nair', 'Sophia Singh', 'Anderson Sneha',
       'Divya Smith', 'Priya Verma', 'Sneha Clark', 'Karan Clark',
       'John Hall', 'Emma Clark', 'Olivia Reddy', 'Reddy Karan',
       'James Smith', 'James Reddy ', 'Liam Lewis ', 'Arjun Lewis',
       'William Nair', 'Rohan Iyer', 'Priya Brown', 'John Nair ',
       'Sophia Reddy', 'Vikram Walker', 'Noah Anderson ', 'Aarav Brown',
       'Anjali Malhotra', 'Anjali Brown', 'Vikram Malhotra ',
       'Arjun Wilson', 'Isabella Verma', 'Emma Wilson', 'Emma Walker',
       'John Wilson', 'Emma Anderson ', 'Priya Gupta', 'Arjun Anderson',
       'Lewis Meera', 'Emma Singh', 'Divya Sharma', 'Smith Anjali',
       'Liam Smith', 'Sophia Clark', 'Sophia Malhotra', 'Arjun Wilson ',
       'Vikram Chopra', 'Liam Chopra', 'Noah Brown ', 'Patel Aarav',
       'James Sharma', 'Meera Lewis', 'Priya Smith', 'Aarav Lewis',
       'Meera Iyer ', 'Sneha Nair', 'Rohan Johnson', 'Sophia Nair',
       'Divya Iyer', 'Vikram Johnson', 'Verma Meera'], dtype=object)

In [387]:
text_df['email'] = text_df['email'].str.lower()
text_df['email'] = (
    text_df['email'].str.replace(r'[.-]','',regex=True)
    .replace('invalidemail', np.nan)
    .str.replace(r'dotcom$', '.com', regex=True)
    .str.replace(r'at(gmail|yahoo|outlook|company)', r'@\1', regex=True)
    .str.replace(r'(gmail|yahoo|outlook)com$', r'\1.com', regex=True).str.strip()
    .str.replace(r'companycoin$', 'company.co.in', regex=True)
    .str.replace(r'(gmail|yahoo|outlook)$', r'\1.com', regex=True)
    .str.replace('DOT', '.', regex=False).str.replace('AT', '@', regex=False)
)
text_df['email'].unique()

array(['johnsingh50@company.co.in', 'vermadivya@gmail.com',
       'divyagupta@gmail.com', nan, 'sophiachopra@yahoo.com',
       'liambrown@outlook.com', 'choprarohan@yahoocom',
       'emmajohnson@gmailcom', 'choprajohn@outlookcom',
       'karananderson@outlook.com', 'johntaylor327@yahoo.com',
       'priyaclark@gmailcom', 'anjalireddy@outlook.com',
       'jamesverma@gmail.com', 'emmapatel572@outlook.com',
       'meeraverma@gmailcom', 'meeragupta@gmail.com',
       'avaanderson@yahoocom', 'priyamalhotra@gmail.com',
       'avanair@gmail.com', 'karanbrown418@gmail.com',
       'snehamalhotra@yahoo.com', 'aaravwilson@outlook.com',
       'liamgupta@company.co.in', 'isabellanair@gmailcom',
       'noahclark24@gmail.com', 'williamgupta@gmail.com',
       'williamiyer@yahoocom', 'arjuniyer@gmail.com',
       'anjalijohnson30@company.co.in', 'karanmalhotra@yahoo.com',
       'rohanwalker447@gmail.com', 'sophiapatel@yahoo.com',
       'snehareddy@gmailcom', 'johnsharma930@outlook.com',
       'williampatel@company.co.in', 'isabellagupta@gmail.com',
       'vikramwilson105@gmail.com', 'sophiawilson@company.co.in',
       'noahchopra287@yahoo.com', 'noahgupta612@yahoo.com',
       'noahsingh@outlookcom', 'sophiasingh991@gmail.com',
       'divyasmith@gmail.com', 'priyaverma@company.co.in',
       'snehaclark@yahoo.com', 'oliviachopra@outlook.com',
       'johnhall@yahoo.com', 'karanreddy@gmail.com',
       'jamessmith@company.co.in', 'arjunlewis@gmail.com',
       'priyabrown@gmail.com', 'johnnair936@company.co.in',
       'sophiareddy@gmail.com', 'aaravbrown@yahoocom',
       'anjalimalhotra@gmailcom', 'arjunwilson@gmail.com',
       'isabellaverma@gmail.com', 'emmawilson362@gmail.com',
       'walkeremma@gmail.com', 'wilsonjohn@yahoocom',
       'arjunanderson@gmail.com', 'meeralewis@gmail.com',
       'anjalismith594@gmail.com', 'liamsmith@gmail.com',
       'malhotrasophia@yahoo.com', 'vikramchopra@gmail.com',
       'liamchopra206@gmail.com', 'priyasmith@gmail.com',
       'nairsneha@gmail.com', 'meeraverma@yahoo.com',
       'iyerdivya839@company.co.in', 'vikramjohnson@gmailcom',
       'meeraverma@company.co.in'], dtype=object)

In [389]:
text_df['city'] = text_df['city'].str.title().str.strip()
text_df['city'] = text_df['city'].str.replace('Bengaluru','Bangalore', regex=True)
text_df['city'] = text_df['city'].replace({'Nyc': 'New York','Delhi' :'New Delhi' })
text_df['city'].unique()

array(['Mumbai', 'New York', 'Bangalore', nan, 'New Delhi', 'London',
       'Toronto'], dtype=object)

In [ ]:
text_df['country'] = text_df['country'].str.strip().str.title()
new_list = {
'Uk' : 'United Kingdom',
'U.K.' :'United Kingdom', 
'In' : 'India',
'U.S.A' : 'United States Of America',
'Usa' :  'United States Of America',
'Us' :  'United States Of America'
}

text_df['country'] = text_df['country'].replace(new_list, regex=False)
text_df['country'].unique()

array(['United States Of America', 'India', 'United Kingdom', 'Canada',
       'Not Provided', 'Australia'], dtype=object)

In [391]:
text_df['gender'] = text_df['gender'].str.title().str.strip()
edit_list = {
    'F' : 'Female',
    'M' : 'Male'
}
text_df['gender'] = text_df['gender'].replace(edit_list, regex=False)

In [392]:
text_df['address'] = text_df['address'].str.title().str.strip().str.rstrip(',. ')
text_df['address'] = text_df['address'].str.title().str.replace(r'\bMg\b', 'MG', regex=True)

In [393]:
text_df['job_title'] = text_df['job_title'].str.title()
text_df['job_title'] = text_df['job_title'].str.replace(r'\s+',' ', regex=True)
edit_list = {
   'Sr. Software Engineer' :  'Sr Software Engineer',
   'Software Engineer' : 'Sr Software Engineer',
   'Sr Sr Software Engineer' : 'Sr Software Engineer',
}

text_df['job_title'] = text_df['job_title'].replace(edit_list, regex=False)
text_df['job_title'].unique()

array(['Sr Software Engineer', 'Marketing Specialist', 'Sales Executive',
       'Hr Executive', 'Data Analyst', nan, 'Product Manager'],
      dtype=object)

In [394]:
text_df['department'] = text_df['department'].str.title()
text_df['department'] = text_df['department'].replace({'Hr': 'Human Resources'})
text_df['department'].unique()

array(['Marketing', 'Sales', 'Product', 'Human Resources', 'Engineering',
       nan, 'Finance'], dtype=object)

In [395]:
text_df['company_name'] = text_df['company_name'].str.title().str.strip('.').str.replace('&','And', regex=False)
text_df['company_name'] = text_df['company_name'].replace('Global Traders Pvt. Ltd', 'Global Traders Pvt Ltd', regex=False)

text_df['company_name'].unique()

array(['Startup Hub', 'Global Traders Pvt Ltd', 'Tech Solutions Inc',
       'Acme And Co', 'Bright Future Llc', nan], dtype=object)

In [397]:
text_df['product_category'] = text_df['product_category'].str.title().str.strip('.').str.replace('&','And', regex=False)
text_df['product_category'] = text_df['product_category'].str.replace('Homeandkitchen' , 'Home And Kitchen', regex=False)
text_df['product_category'].unique()

array(['Electronics', 'Beauty', 'Sports And Fitness', 'Clothing',
       'Home And Kitchen', nan, 'Books'], dtype=object)

In [398]:
text_df['feedback_text'] = (
    text_df['feedback_text'].str.replace(r'[!,-.:(]' , ' ', regex=True )
    .str.replace(r'\s+' ,' ', regex=True)
    .str.replace('&amp;', '&', regex=False)
)
text_df['feedback_text'] = text_df['feedback_text'].str.title().str.strip()

In [399]:
text_df['status'] = text_df['status'].str.title().str.strip()
edit_list = {
    'A' : 'Active',
    'I' : 'Inactive'
}
text_df['status'] = text_df['status'].replace(edit_list, regex=False)

In [400]:
text_df['notes'] = text_df['notes'].str.replace(r'[!,-.]' , ' ', regex=True ).str.replace(r'\s+',' ', regex=True)
text_df['notes'] = text_df['notes'].str.title().str.strip()

In [401]:
text_df['phone_number'] = text_df['phone_number'].str.strip()
text_df['phone_number'] = (
    text_df['phone_number'].str.replace(r'[,-.()]' , '', regex=True )
    .str.replace(r'\s+', '', regex=True)
    .replace('unknown',np.nan).str.lstrip('0')
    .str.replace(r'^\+91', '', regex=True)
    .str.replace(r'\D', '', regex=True)
)

text_df['phone_number'] = text_df['phone_number'].where(text_df['phone_number'].str.len() == 10, np.nan)

In [402]:
text_df['phone_number'].unique()

array([nan, '2819482199', '3212233079', '6031372159', '7353799075',
       '7299752882', '1803340187', '5058770658', '9751402614',
       '4023448347', '4335326502', '5585304352', '3198296572',
       '0837407188', '5449920707', '1874633191', '6565150556',
       '6853560688', '4634786122', '3066683645', '7970168773',
       '6111489364', '7923760926', '7046557210', '3557063606',
       '0788526114', '5443732332', '3056529413', '2542821167',
       '9773797276', '2019132742', '2624562418', '3694923597',
       '7320008062', '6717231430', '3659368778', '0201019538',
       '6160534468', '4932573834', '6393217654', '4660016659',
       '2567482753', '6019528590', '4373817181', '9747566125',
       '8689064100', '7320600113', '9959029496', '8758188763',
       '8578933331', '5489010397', '7719611459', '6204207858',
       '7423293943', '0259905878', '3922144800', '4111628933',
       '8091418063', '9443184799', '6052358574', '2655239948',
       '2367679958', '3836209915', '8829369122', '7469471369',
       '6561165836', '1846092406', '1862297631', '8214956255',
       '8918991617', '4700527870', '3522307676', '1752448024',
       '9506952102', '8842408715', '6335356447', '3507262401',
       '7153314204', '7857907785', '9409248454', '4669453692',
       '6672176728', '3970357086', '4382238171', '7507137449',
       '7355214187', '1507424113', '8831010793', '5107078519',
       '6684981143'], dtype=object)

In [411]:
text_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                140 non-null    int64
 1   full_name         140 non-null    object
 2   email             140 non-null    object
 3   phone_number      140 non-null    object
 4   gender            140 non-null    object
 5   country           140 non-null    object
 6   city              140 non-null    object
 7   address           140 non-null    object
 8   job_title         140 non-null    object
 9   department        140 non-null    object
 10  company_name      140 non-null    object
 11  product_category  140 non-null    object
 12  feedback_text     140 non-null    object
 13  status            140 non-null    object
 14  notes             140 non-null    object
dtypes: int64(1), object(14)
memory usage: 16.5+ KB

In [404]:
text_df.drop_duplicates(inplace=True)
text_df.reset_index(drop=True, inplace=True)

 ## try fill null values

In [414]:
text_cols = ['gender','country','city','job_title','department','company_name',
             'product_category','feedback_text','status','notes']
text_df[text_cols] = text_df[text_cols].fillna('Not Provided')

In [407]:
text_cols = ['email','phone_number','address']
text_df[text_cols] = text_df[text_cols].fillna('Unknown')

In [413]:
text_df.to_csv('clean_dataset_2.csv', index=False)