In [418]:
import pandas as pd
import numpy as np

In [419]:
num_df = pd.read_csv(r'D:\DA_data\Data_analytics\power Bi project\Upi Transaction\Cleaning_prectice\numeric_data_cleaning\Raw\messy_numeric_data.csv')

In [420]:
num_df.sample(12)

,id,age,salary,height_cm,weight_kg,bmi,temperature_c,blood_pressure,heart_rate,test_score,monthly_expense,account_balance,discount_percent,quantity_ordered,rating
76,134,39,not disclosed,999,0.0,31.6,97.5,136,82.0,74,"Rs.31,492",187981.98,26.4%,42,5 stars
101,124,234,-82567,unknown,0.0,29.5,97.9,-120,56.0,-10,33004.00,"61,816.65",35.2,-5,4.9
137,118,NaN,66588,-170,59.9,21.4,NaN,120/80,NaN,-10,NaN,"162,082.38",-15,NaN,10
97,25,39,NaN,173.7,76.3,-5.0,97.9,99,NaN,57,-28460,"65,289.26",32.2,8,NaN
67,37,-5,not disclosed,NaN,67.0,150.0,98.5,NaN,-70.0,absent,NaN,1.5e5,48.9%,0,2.9
145,93,twenty,90457,0.73,72.3,NaN,212,113,300.0,-10,"Rs.34,880",1.5e5,NaN,NaN,-1
139,60,twenty,144k,0.66,-60.0,NaN,0,100,300.0,150,NaN,NaN,150,49,good
105,53,NaN,117024,190.0,NaN,NaN,212,-120,NaN,4,33314.00,"178,916.21",NaN,NaN,good
28,18,19,"$53,529",999,0.0,32.1,37.2,-120,NaN,NaN,NaN,133535.71,NaN,25,-1
135,129,47,84817,165.2,0.0,29.3,NaN,400,300.0,-10,NaN,NaN,9.4%,34,NaN
106,100,-10,118820,-170,46.2,20.5,97.8,105,NaN,150,NaN,1.5e5,none,44,4.4
94,114,44,48669,0.71,89.7,-5.0,37.5,NaN,300.0,37,"Rs.18,319","85,871.88",43.6,3,10

In [421]:
num_df.sort_values(by= 'id', inplace=True, ascending=True)
num_df.reset_index(drop=True, inplace=True)
num_df.head(10)

,id,age,salary,height_cm,weight_kg,bmi,temperature_c,blood_pressure,heart_rate,test_score,monthly_expense,account_balance,discount_percent,quantity_ordered,rating
0,1,twenty,"$135,530",171.4,-60.0,24.1,36.5,-120,-70.0,78,NaN,96998.23,32.4,10,1.1
1,2,39,not disclosed,999,0.0,150.0,212,-120,76.0,NaN,-25935,NaN,49.7,few,-1
2,3,NaN,NaN,999,-60.0,19.2,normal,400,-70.0,150,2934.00,1.5e5,46.8%,-5,-1
3,4,21,"$79,991",153.1,-60.0,NaN,NaN,NaN,-70.0,-10,"Rs.22,183",NaN,-15,44,2.3
4,5,34,43607,999,101.4,-5.0,36.4,-120,NaN,70,NaN,98500.34,-15,0,NaN
5,6,NaN,45k,999,NaN,NaN,normal,400,300.0,NaN,6280.00,1.5e5,5.4,0,good
6,7,NaN,-139775,153.2,0.0,-5.0,normal,148,85.0,absent,"Rs.41,622",closed,none,-5,10
7,8,NaN,51k,182.2,0.0,34.7,NaN,400,NaN,NaN,35729.00,"188,715.99",25.4%,few,-1
8,9,47,-112512,154.5,0.0,150.0,normal,118,89.0,-10,26285,"70,859.06",-15,4,4.5
9,10,54,-35543,183.6,NaN,NaN,NaN,120/80,95.0,8,35538,"133,991.88",17.6%,NaN,3.6

In [422]:
num_df['age'] = num_df['age'].str.replace(r'[-]','',regex=True)

In [423]:
num_df['age'] = num_df['age'].replace('twenty','20')
num_df['age'] = pd.to_numeric(num_df['age'])
num_df.loc[num_df['age'] > 100, 'age'] = np.nan

# i am using random value function but mostly we uses the mean(), median(), mode
missing_val = num_df['age'].isnull().sum()
random_val = np.random.randint(18, 60 ,size=missing_val)
num_df.loc[num_df['age'].isnull(), 'age'] = random_val
num_df['age'] = num_df['age'].astype(int)

In [424]:
num_df['age'].unique()

array([20, 39, 31, 21, 34, 55, 36, 33, 47, 54, 19, 27,  8, 40,  5, 63,  9,
       43, 59, 25, 38,  6, 42, 46,  4,  3, 48, 32,  7, 35, 30, 22, 50, 44,
       41, 58, 65, 23, 52, 60, 29, 57, 24, 26, 18, 10, 49, 56, 61, 53, 37,
        2, 51])

In [425]:
num_df['salary'].unique()

array(['$135,530', 'not disclosed', nan, '$79,991', '43607', '45k',
       '-139775', '51k', '-112512', '-35543', '$78,532', '$58,154',
       '138k', '$119,993', '63k', '$53,529', '62k', '  61640  ',
       '-108948', '  124147  ', '$132,186', '123k', '  65695  ', '139820',
       '$43,317', '$116,873', '  93214  ', '$133,503', '-128159',
       '  100524  ', '$100,111', '  125212  ', '117024', '-31687',
       '58366', '57643', '$26,509', '144k', '  116802  ', '  111686  ',
       '-69861', '-45610', '  36041  ', '107k', '  77929  ', '49k', '72k',
       '  58824  ', '-77406', '  68363  ', '  42334  ', '$38,760',
       '$72,787', '$65,572', '-90584', '39k', '$108,871', '$33,225',
       '$100,677', '114239', '56199', '135077', '90457', '$74,026',
       '122032', '79k', '118820', '140k', '34k', '$104,066', '149827',
       '118475', '55127', '  39886  ', '  128345  ', '  48669  ',
       '$59,355', '115k', '  86681  ', '66588', '-141002', '86k',
       '-61065', '-82567', '  85806  ', '84817', '68k', '-77653', '74k',
       '$110,959', '$73,455', '-71930', '$44,078', '41462', '$92,575'],
      dtype=object)

In [426]:
num_df['salary'] = num_df['salary'].str.replace('k', '000', regex=True)
num_df['salary'] = num_df['salary'].str.replace(r'[-,$]','',regex=True).str.strip()

In [427]:
num_df['salary'] = num_df['salary'].replace('not disclosed',np.nan, regex=True)

In [428]:
num_df['salary'] = pd.to_numeric(num_df['salary'], errors='coerce')

In [429]:
# this is not good way but i am just doing for make real
missing_val = num_df['salary'].isnull().sum()
random_val = np.random.randint(40000,95000,size=missing_val)
num_df.loc[num_df['salary'].isnull(), 'salary'] = random_val

In [430]:
num_df['height_cm'] = num_df['height_cm'].str.replace(r'[-]','',regex=True)
num_df['height_cm'] = pd.to_numeric(num_df['height_cm'], errors='coerce')

In [431]:
num_df.loc[num_df['height_cm'] == 999.00, 'height_cm'] = np.nan

In [432]:
# this is not good way but i am just doing for make real
missing_val = num_df['height_cm'].isnull().sum()
random_val = np.random.randint(50,150,size=missing_val)
num_df.loc[num_df['height_cm'].isnull(), 'height_cm'] = random_val

In [433]:
num_df[(num_df['weight_kg'] == 0.0) | (num_df['weight_kg'] == -60.0)]
num_df.loc[num_df['weight_kg'].isin([0.0, -60.0]), 'weight_kg'] = np.nan

In [434]:
# this is not good way but i am just doing for make real
missing_val = num_df['weight_kg'].isnull().sum()
random_val = np.random.randint(50,150,size=missing_val)
num_df.loc[num_df['weight_kg'].isnull(), 'weight_kg'] = random_val

In [435]:
num_df['bmi'] = num_df['bmi'].replace(-5.0, 5.0)
num_df.loc[num_df['bmi'] == 150, 'bmi'] = np.nan

In [436]:
# this is not good way but i am just doing for make real
missing_val = num_df['bmi'].isnull().sum()
random_val = np.random.randint(20,60,size=missing_val)
num_df.loc[num_df['bmi'].isnull(), 'bmi'] = random_val

In [437]:
mean_val = num_df['bmi'].median()
num_df['bmi'].fillna(mean_val,inplace=True)

C:\Users\siddh\AppData\Local\Temp\ipykernel_14588\3281824976.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  num_df['bmi'].fillna(mean_val,inplace=True)

In [438]:
num_df['temperature_c']= num_df['temperature_c'].replace([0,'normal'], np.nan)
num_df['temperature_c'] = pd.to_numeric(num_df['temperature_c'], errors='coerce')

In [439]:
num_df.loc[num_df['temperature_c'] > 70, 'temperature_c'] = np.nan

In [440]:
# this is not good way but i am just doing for make real
missing_val = num_df['temperature_c'].isnull().sum()
random_val = np.random.randint(20,60,size=missing_val)
num_df.loc[num_df['temperature_c'].isnull(), 'temperature_c'] = random_val

In [441]:
num_df['blood_pressure'] = num_df['blood_pressure'].str.split('/').str[0]
num_df['blood_pressure'] = num_df['blood_pressure'].str.replace('-','', regex=False)
num_df['blood_pressure'] = pd.to_numeric(num_df['blood_pressure'], errors='coerce')

In [442]:
num_df.loc[num_df['blood_pressure'] > 180, 'blood_pressure'] = np.nan

In [443]:
bp = round(num_df['blood_pressure'].mean())
num_df['blood_pressure'] = num_df['blood_pressure'].fillna(bp)
num_df['blood_pressure'] = num_df['blood_pressure'].astype(int)

In [444]:
num_df['heart_rate'] = num_df['heart_rate'].replace(-70,70, regex=True)
num_df.loc[num_df['heart_rate'] > 180, 'heart_rate'] = np.nan

In [445]:
# this is not good way but i am just doing for make real
missing_val = num_df['heart_rate'].isnull().sum()
random_val = np.random.randint(70,120,size=missing_val)
num_df.loc[num_df['heart_rate'].isnull(), 'heart_rate'] = random_val

In [446]:
num_df['test_score'] = (
    num_df['test_score'].str.replace('absent','0', regex=True)
    .str.replace('-10','10')
)
num_df['test_score'] = pd.to_numeric(num_df['test_score'])

In [472]:
num_df.loc[num_df['test_score'] > 100, 'test_score'] = np.nan

In [473]:
ts = round(num_df['test_score'].mean())
num_df['test_score'] = num_df['test_score'].fillna(ts)
num_df['test_score'] = num_df['test_score'].astype(int)

In [448]:
num_df['monthly_expense'] = (
     num_df['monthly_expense'].str.replace(r'[-,]','',regex=True)
     .str.strip('Rs.').str.strip('.00')
)

In [449]:
# this is not good way but i am just doing for make real
missing_val = num_df['monthly_expense'].isnull().sum()
random_val = np.random.randint(10000,32000,size=missing_val)
num_df.loc[num_df['monthly_expense'].isnull(), 'monthly_expense'] = random_val
num_df['monthly_expense'] = pd.to_numeric(num_df['monthly_expense'], errors='coerce')

In [450]:
num_df['account_balance'].str.replace(r'[-,]','',regex=True)
num_df['account_balance'] = pd.to_numeric(num_df['account_balance'], errors='coerce')

In [451]:
# this is not good way but i am just doing for make real
missing_val = num_df['account_balance'].isnull().sum()
random_val = np.random.randint(10000,32000,size=missing_val)
num_df.loc[num_df['account_balance'].isnull(), 'account_balance'] = random_val

In [452]:
num_df['discount_percent'] = num_df['discount_percent'].str.replace(r'[-%]','',regex=True)
num_df['discount_percent'] = pd.to_numeric(num_df['discount_percent'], errors='coerce')

In [453]:
num_df.loc[num_df['discount_percent'] == 150, 'discount_percent'] = np.nan

In [454]:
# this is not good way but i am just doing for make real
missing_val = num_df['discount_percent'].isnull().sum()
random_val = np.random.randint(20,70,size=missing_val)
num_df.loc[num_df['discount_percent'].isnull(), 'discount_percent'] = random_val

In [455]:
num_df['quantity_ordered'].str.strip().str.replace('-','',regex=True)
num_df['quantity_ordered'] = pd.to_numeric(num_df['quantity_ordered'], errors='coerce')
num_df['quantity_ordered'] = num_df['quantity_ordered'].replace(-5,5,regex=True)

In [456]:
mean_val = round(num_df['quantity_ordered'].mean())
num_df['quantity_ordered'] = num_df['quantity_ordered'].fillna(mean_val)

In [457]:
num_df['quantity_ordered']= num_df['quantity_ordered'].astype(int)

In [458]:
num_df['rating'] = (
    num_df['rating'].str.replace('-','',regex=True)
    .replace('good',np.random.randint(2.0, 3.5),regex=True)
    .replace('5 stars',5,regex=True)
)

In [459]:
num_df['rating'] = pd.to_numeric(num_df['rating'], errors='coerce')

In [460]:
# this is not good way but i am just doing for make real
missing_val = num_df['rating'].isnull().sum()
random_val = np.random.randint(1,6,size=missing_val)
num_df.loc[num_df['rating'].isnull(), 'rating'] = random_val

In [476]:
num_df.loc[num_df['rating'] > 6, 'rating'] = np.nan
rating_mean = num_df['rating'].median()

num_df['rating'] = num_df['rating'].fillna(rating_mean).astype(int)

In [461]:
num_df['rating']= num_df['rating'].astype(int)

In [477]:
num_df.sample(20)

,id,age,salary,height_cm,weight_kg,bmi,temperature_c,blood_pressure,heart_rate,test_score,monthly_expense,account_balance,discount_percent,quantity_ordered,rating
119,120,54,53410.0,164.70,100.0,42.0,36.0,120,106.0,0,5138,20910.00,35.0,44,4
32,33,38,40680.0,92.00,94.6,28.0,38.0,115,94.0,33,30497,21240.00,15.0,9,3
16,17,34,63000.0,104.00,82.0,22.0,21.0,120,83.0,10,20080,150000.00,49.0,17,2
73,74,24,77406.0,104.00,58.0,29.0,22.0,120,77.0,72,32744,160976.14,29.0,17,2
50,51,22,125212.0,0.79,59.3,49.0,36.8,120,70.0,69,50667,11762.00,53.0,33,5
23,24,9,108948.0,170.00,62.0,5.0,58.0,120,70.0,33,50007,31839.00,25.0,17,4
43,44,7,88470.0,1.83,46.5,5.0,0.0,120,70.0,33,32677,17808.00,53.0,0,1
6,7,36,139775.0,153.20,106.0,5.0,43.0,148,85.0,0,41622,18553.00,31.0,5,2
20,21,63,76861.0,170.00,133.0,21.7,36.9,120,80.0,23,26082,84842.49,44.0,36,2
44,45,35,60305.0,85.00,84.0,34.3,37.0,100,100.0,13,23502,161930.61,22.0,0,1
79,80,26,65572.0,95.00,110.0,37.0,0.0,120,70.0,33,21608,150000.00,0.8,5,2
29,30,59,83076.0,150.70,52.0,5.0,37.3,120,100.0,18,44454,10428.00,19.3,22,5
128,129,47,84817.0,165.20,143.0,29.3,38.0,120,113.0,10,28784,10773.00,9.4,34,4
109,110,43,92780.0,176.50,69.5,51.0,23.0,113,88.0,53,33911,19316.00,13.6,47,5
114,115,22,59355.0,184.70,127.0,21.5,37.6,120,71.0,97,5482,20349.40,56.0,5,2
74,75,8,92906.0,55.00,66.5,33.3,0.0,120,67.0,4,23181,29253.00,15.0,29,2
31,32,20,62923.0,170.00,141.0,34.5,34.0,114,77.0,33,58306,150000.00,15.8,0,5
138,139,57,41462.0,164.30,53.6,35.0,39.0,131,65.0,98,27423,28704.00,15.0,5,1
132,133,20,56635.0,160.00,47.5,27.2,29.0,120,77.0,0,24619,150000.00,48.7,17,1
80,81,18,90584.0,1.81,60.0,34.6,21.0,114,85.0,75,10978,128501.15,44.4,17,5

In [475]:
num_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                140 non-null    int64
 1   age               140 non-null    int64
 2   salary            140 non-null    float64
 3   height_cm         140 non-null    float64
 4   weight_kg         140 non-null    float64
 5   bmi               140 non-null    float64
 6   temperature_c     140 non-null    float64
 7   blood_pressure    140 non-null    int64
 8   heart_rate        140 non-null    float64
 9   test_score        140 non-null    int64
 10  monthly_expense   140 non-null    int64
 11  account_balance   140 non-null    float64
 12  discount_percent  140 non-null    float64
 13  quantity_ordered  140 non-null    int64
 14  rating            140 non-null    int64
dtypes: float64(8), int64(7)
memory usage: 16.5 KB

In [470]:
num_df.drop_duplicates(subset=['id'], inplace=True)
num_df.reset_index(drop=True, inplace=True)

In [478]:
num_df.to_csv('clened_3.csv', index=False)